//* IMPORT: data
import data from '../config/data.json';

//* IMPORT: types
import { iDataProps } from '../config/data-type';

//* IMPORT: nextjs-features-types
import Head from 'next/head';
import type { AppProps } from 'next/app';

//* IMPORT: components
import { LayoutHome } from '../components/components';

//* IMPORT: styling
import '../styles/globals.css';

interface iApp {
    Component: any;
    pageProps: AppProps;
    data: iDataProps;
}


function App({ Component, pageProps }: iApp) {
    const {footer}: iDataProps = data;
    return (
        <>
            <Head>
                <meta 
                    name="description" 
                    content="Generated by create next app" 
                />
                <meta 
                    name="viewport" 
                    content="width=device-width, initial-scale=1" 
                />
                <link 
                    rel="icon" 
                    href="/favicon.ico" 
                />
            </Head>
            <LayoutHome footer={footer}>
                <Component {...pageProps} />
            </LayoutHome>
        </>
    )

}

export default App;


